# Generated by Django 5.1.6 on 2025-04-17 17:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Attribute",
            fields=[
                (
                    "attribute_id",
                    models.AutoField(
                        primary_key=True, serialize=False, verbose_name="attribute_id"
                    ),
                ),
                ("name", models.TextField(verbose_name="name")),
                ("data_type", models.TextField(verbose_name="data_type")),
            ],
            options={
                "verbose_name": "Attribute",
                "verbose_name_plural": "Attributes",
                "db_table": "attributes",
                "managed": True,
            },
        ),
        migrations.CreateModel(
            name="Product",
            fields=[
                (
                    "product_id",
                    models.AutoField(
                        primary_key=True, serialize=False, verbose_name="product_id"
                    ),
                ),
                ("name", models.CharField(max_length=255, verbose_name="name")),
                (
                    "category",
                    models.CharField(
                        blank=True, max_length=255, null=True, verbose_name="category"
                    ),
                ),
                (
                    "parameters",
                    models.JSONField(
                        blank=True, default=dict, null=True, verbose_name="parameters"
                    ),
                ),
            ],
            options={
                "verbose_name": "Product",
                "verbose_name_plural": "Products",
                "db_table": "products",
                "managed": True,
            },
        ),
        migrations.CreateModel(
            name="TimeSeries",
            fields=[
                (
                    "time_series_id",
                    models.AutoField(
                        primary_key=True, serialize=False, verbose_name="time_series_id"
                    ),
                ),
                ("name", models.TextField(verbose_name="name")),
                (
                    "parent_time_series",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="databaseadmin.timeseries",
                        verbose_name="parent_time_series",
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="databaseadmin.product",
                        verbose_name="product",
                    ),
                ),
            ],
            options={
                "verbose_name": "Time Series",
                "verbose_name_plural": "TimeSeries",
                "db_table": "time_series",
                "managed": True,
            },
        ),
        migrations.CreateModel(
            name="ForecastingModel",
            fields=[
                (
                    "model_id",
                    models.AutoField(
                        primary_key=True, serialize=False, verbose_name="model_id"
                    ),
                ),
                ("trained_model", models.BinaryField(verbose_name="trained_model")),
                (
                    "feature_attribute",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="feature_models",
                        to="databaseadmin.attribute",
                        verbose_name="feature_attribute",
                    ),
                ),
                (
                    "target_attribute",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="target_models",
                        to="databaseadmin.attribute",
                        verbose_name="target_attribute",
                    ),
                ),
                (
                    "time_series",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="databaseadmin.timeseries",
                        verbose_name="time_series",
                    ),
                ),
            ],
            options={
                "verbose_name": "Forecasting Model",
                "verbose_name_plural": "Forecasting Models",
                "db_table": "forecasting_models",
                "managed": True,
            },
        ),
        migrations.CreateModel(
            name="Timestamp",
            fields=[
                (
                    "timestamp_id",
                    models.AutoField(
                        primary_key=True, serialize=False, verbose_name="timestamp_id"
                    ),
                ),
                ("value", models.TextField(verbose_name="value")),
                ("start_dt", models.DateTimeField(verbose_name="start_dt")),
                (
                    "end_dt",
                    models.DateTimeField(blank=True, null=True, verbose_name="end_dt"),
                ),
                (
                    "attribute",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="databaseadmin.attribute",
                        verbose_name="attribute",
                    ),
                ),
                (
                    "time_series",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="databaseadmin.timeseries",
                        verbose_name="time_series",
                    ),
                ),
            ],
            options={
                "verbose_name": "Timestamp",
                "verbose_name_plural": "Timestamps",
                "db_table": "timestamps",
                "managed": True,
            },
        ),
    ]
