# Generated by Django 5.1.6 on 2025-04-17 22:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("databaseadmin", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="forecastingmodel",
            name="model_file_path",
            field=models.CharField(
                blank=True, max_length=255, null=True, verbose_name="model_file_path"
            ),
        ),
        migrations.AlterField(
            model_name="forecastingmodel",
            name="trained_model",
            field=models.BinaryField(
                blank=True, null=True, verbose_name="trained_model"
            ),
        ),
    ]
